config/routes.rb
Rails.application.routes.draw do
  resources :my_updates
  devise_for :users
  get 'static_pages/home'
  resources :users
  resources :manager
  get '/dashboard',to: 'manager#done'
  get '/action_page.php', to: 'manager#create'
  get 'static_pages/help'
  root 'static_pages#home'
  get  'static_pages/about'
  get  '/signup',  to: 'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/manager.rb
class Manager < ApplicationRecord
  belongs_to :user
  validates_uniqueness_of :user_id
end

app/models/my_update.rb
class MyUpdate < ApplicationRecord
  belongs_to :user
  # attr_accessor :date
  validates :content, presence: true
  validates :title, presence: true

end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :managers, dependent: :destroy
  has_many :my_updates
end

#has_many :manager_user, class_name: 'User', foriegn_key: 'manager_user_id'
#has_many :user, class_name: 'User', foriegn_key: 'user_id'

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

    def hello
    render html: "hello, world!"
  end
end

app/controllers/manager_controller.rb
class ManagerController < ApplicationController
#before_action :authenticate_user!
  def create
  	employee_id=params[:employee]
  	manager_id=params[:manager]
  	if employee_id == manager_id
     flash[:success]="cant have both same name"
     redirect_to  manager_index_path
    else
      	manager_user=Manager.new
      	manager_user.user_id=employee_id
      	manager_user.manager_user_id=manager_id
          if manager_user.save
           flash[:success]="saved to table"
           redirect_to  manager_index_path
           else
            flash[:success]="cant have 1 user with diffrent manager"
            redirect_to  manager_index_path
          end
    end     
  end
  def index
  	@managers= Manager.all
    @mys= Manager.where(manager_user_id: current_user.id)
    @test = params[:test]
  end
 end

app/controllers/my_updates_controller.rb
class MyUpdatesController < ApplicationController
  before_action :set_my_update, only: [:edit, :update]

  # GET /my_updates
  # GET /my_updates.json
  def index
    if params[:id].present?
      @my_updates = MyUpdate.where(user_id: params[:id]).order('created_at DESC')
      @type="id"
    else 
      if params[:search][:date].present?
      @type="date"
      if params[:search][:idt].present?
      @my_updates = MyUpdate.where(date: params[:search][:date], user_id: params[:search][:idt].split(' ')).order('created_at DESC')
      #puts @my_updates.count.inspect
      else
      flash[:success] = "Sorry!!!There is no user under you"
      redirect_to  manager_index_path 
      end
      else
        flash[:success] = "no data for this date"
      redirect_to  manager_index_path 
      end
    end
  end
  # GET /my_updates/1
  # GET /my_updates/1.json
  def show
    @my_update = MyUpdate.where(user_id: params[:id])
  end
   
   # GET /my_updates/new
  def new
    @my_update = MyUpdate.new
  end

  # GET /my_updates/1/edit
  def edit
  end

  # POST /my_updates
  # POST /my_updates.json
  def create
    #params[:my_update][:date]
    @my_update = MyUpdate.new(my_update_params)
    @my_update.user_id = current_user.id
    #@my_update.date = params[:date]
    @my_update.save
    respond_to do |format|
      if @my_update.save
        format.html { redirect_to @my_update, notice: 'My update was successfully created.' }
        format.json { render :show, status: :created, location: @my_update }
      else
        format.html { render :new }
        format.json { render json: @my_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_updates/1
  # PATCH/PUT /my_updates/1.json
  def update
    respond_to do |format|
      if @my_update.update(my_update_params)
        format.html { redirect_to @my_update, notice: 'My update was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_update }
      else
        format.html { render :edit }
        format.json { render json: @my_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_updates/1
  # DELETE /my_updates/1.json
  def destroy
    @my_update.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_update
      @my_update = MyUpdate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_update_params
        # my=MyUpdate.new
        # my.user_id =current_user.id
      params.require(:my_update).permit(:title, :content, :user_id, :date)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  def about
  	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
 def index
 	@users = User.all
 	@managers = Manager.all
 end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.       # Documentation comment
  def full_title(page_title = '')                     # Method def, optional arg
    base_title = "Ruby on Rails Tutorial Sample App"  # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      page_title + " | " + base_title                 # String concatenation
    end
  end
end

app/helpers/manager_helper.rb
module ManagerHelper

	def mangers_email manager_id
		manager = User.find_by_id(manager_id)
		if manager.present?
			email = manager.email
		else
			email = ""
		end
		email
	end
end

app/helpers/my_updates_helper.rb
module MyUpdatesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/helpers/user_updates_helper.rb
module UserUpdatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
         <li>
          <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
         </li>

        <% else %>
          <li>
            <%= link_to('LOGIN', new_user_session_path)  %>  
          </li>
        <% end %>
        <% unless current_user.nil? %>
          <% if current_user.has_role? :admin %>
            <li>
              <%= link_to('Action', users_path ) %> 
           </li>
           <li>
              <%= link_to('Details', manager_index_path ) %> 
           </li>
          <% else %>
          <li>
              <%= link_to('Users',manager_index_path(test: 'user')) %> 
           </li>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Updates <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
            <li><%= link_to('Add new',  new_my_update_path )  %></li>
             <li> <%= link_to('My updates', my_updates_path(id: current_user.id) )  %>  </li>
             <li> <%= link_to('All updates',manager_index_path)  %>  </li>
            </ul>
          </li>
          <% end %>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/manager/dashboard.html.erb
<h1>welcome</h1>

app/views/manager/index.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
<%idt = []%>
<% if current_user.has_role? :admin %>
 
  <table class="table table-dark" style="width:100%">
    <thead class="thead-dark">
      <tr>
      <th>Manager Name</th>
      <th>Employee Name</th>
      </tr>
    </thead>
    <tbody>
      <% @managers.each do |t| %>
        <tr>
          <td><%= mangers_email(t.manager_user_id)%></td>
          <td><%= t.user.email%></td>
        </tr>
      <%end %>
    </tbody>
  </table>
<%else%>
<%if @test=="user"%>
<h1>Details</h1>
  <table class="table table-dark" style="width:100%">
    <tbody>
      <% @mys.each do |t| %>
        <%if current_user.id == t.manager_user_id%>
          <ul class = "media-list" style="list-style-type:square">
            <li class = "media">
              <div class = "media-body">
                <h4 class = "media-heading"><%= t.user.email%></h4>
                 <%= link_to "Show", my_update_path(id: t.user_id),class: "btn btn-primary"%>
                    <div class = "media" style="margin-left: 40px">
                      <a class = "media-left"> 
                       <% if Manager.where(manager_user_id: t.user.id).present? %>
                       <% Manager.where(manager_user_id: t.user.id).each do |emp| %>
                          <div class = "media" >
                          <h4 class = "media-left"><%= emp.user.email%></h4>
                          <%= link_to "Show", my_update_path(id: emp.user_id),class: 
                          "btn btn-primary "%> 
                          <% if Manager.where(manager_user_id: emp.user.id).present? %>
                          <% Manager.where(manager_user_id: emp.user.id).each do |empp| %>
                          <div class = "media" style="margin-left: 40px">
                          <h4 class = "media-left"><%= empp.user.email%></h4>
                          <%= link_to "Show", my_update_path(id: empp.user_id),class: 
                          "btn btn-primary "%> 
                          <% if Manager.where(manager_user_id: empp.user.id).present? %>
                          <% Manager.where(manager_user_id: empp.user.id).each do |emppp| %>
                          <div class = "media" style="margin-left: 40px">
                          <h4 class = "media-left"><%= emppp.user.email%></h4>
                          <%= link_to "Show", my_update_path(id: emppp.user_id),class: 
                          "btn btn-primary "%> 
                          <% if Manager.where(manager_user_id: emppp.user.id).present? %>
                          <% Manager.where(manager_user_id: emppp.user.id).each do |emppp| %>
                          <div class = "media" style="margin-left: 40px">
                          <h4 class = "media-left"><%= empppp.user.email%></h4>
                          <%= link_to "Show", my_update_path(id: empppp.user_id),class: 
                          "btn btn-primary "%> 
                          <% if Manager.where(manager_user_id: empppp.user.id).present? %>
                          <% Manager.where(manager_user_id: empppp.user.id).each do |emppp| %>
                          <div class = "media" style="margin-left: 40px">
                          <h4 class = "media-left"><%= emppppp.user.email%></h4>
                          <%= link_to "Show", my_update_path(id: emppppp.user_id),class: 
                          "btn btn-primary "%> 
                        </div>
                        <%end%>
                        <%end%>
                        
                        </div>
                        <%end%>
                        <%end%>
                        
                        </div>
                        <%end%>
                        <%end%>
                        
                        </div>
                        <%end%>
                        <%end%>

                        </div>
                        <%end%>
                        <%end%>
                      </a>          
                    </div>
              </div>
            </li>
          </ul>
        <%end%>
      <%end%>  
    </tbody>
  </table>
  <%else%>
  <%= form_for :search , url: my_updates_path ,method: :get do |f| %>
  <div class="field">
    <%= f.text_field :date, id: :date ,class: "datepicker"%>
   </div>
    <div>
  <% @managers.each do |t| %>
      <% if current_user.id == t.manager_user_id%>
          <% idt.push << t.user.id %>
  <%end%>
  <%end%>
    <%=f.hidden_field :idt, value: idt %>
  </div>
   <div class="actions" >
    <%= f.submit  %>
  </div>
 
  <%end%>
<script type="text/javascript">
  $(document).ready(function(){
    $( ".datepicker" ).datepicker({    
  dateFormat: 'dd-mm-YYYY'
  });
  });
</script>
<%end%>
<% end %>





<!-- manager = Manager.find(id)
employee = Manager.where(manager_user_id:manager.id)
employee 1
employee_under = Manager.where(manager_user_id:user_id)
end -->

app/views/my_updates/_form.html.erb
<%= form_with(model: my_update, local: true) do |form| %>
  <% if my_update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(my_update.errors.count, "error") %> prohibited this my_update from being saved:</h2>

      <ul>
      <% my_update.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<!-- <input type="text" class='datepicker' > -->
 <div class="field">
    <%= form.text_field :date, id: :date ,class: "datepicker"%>
  </div>

<script type="text/javascript">
  $(document).ready(function(){
    $( ".datepicker" ).datepicker({    
  dateFormat: 'dd-mm-YYYY'
  });
  });
</script>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :my_update_title %>
  </div>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :my_update_content %>
    <%#= hidden_field_tag :user_id, current_user.id%>
  </div>
  <div class="actions" >
    <%= form.submit  %>
  </div>
<% end %>

app/views/my_updates/edit.html.erb
<h1>Editing My Update</h1>

<%= render 'form', my_update: @my_update %>

<%= link_to 'Show', @my_update %> |
<%= link_to 'Back', my_updates_path %>

app/views/my_updates/index.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
<%if @type =="id"%>
<p id="notice"><%= notice %></p>
<h1>My Updates</h1>
<table>
  <thead>
    <tr>
      <th>Title</th><th></th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_updates.each do |my_update| %>
      <tr>
        <td><%= my_update.title %></td><td></td>
        <td><%= my_update.content %></td><td></td><td></td>

      </tr>
    <% end %>
  </tbody>
</table>
<%else%>
<p id="notice"><%= notice %></p>
<h1>My Updates</h1>
<table>
  <thead>
    <tr>
      <th>Title</th><th></th>
      <th>Content</th><th></th><th></th>
      <th>Email</th><th></th><th></th>
      <th>Date</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_updates.each do |my_update| %>
      <tr>
        <td><%= my_update.title %></td><td></td>
        <td><%= my_update.content %></td><td></td><td></td>
        <td><%= my_update.user.email %></td><td></td><td></td>
        <td><%= my_update.date%></td><td></td><td></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%end%>

app/views/my_updates/new.html.erb
<h1>New My Update</h1>

<%= render 'form', my_update: @my_update %>

app/views/my_updates/show.html.erb
<p id="notice"><%= notice %></p>
<% @my_update.each do |t| %>
<p>
  <strong>Name:</strong>
  <%= t.user.email %>
</p>
<p>
  <strong>Title:</strong>
  <%= t.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= t.content %>
</p>
<p>
  <strong>Date:</strong>
  <%= t.date %>
</p>

<% end %>

app/views/my_updates/updatess.html.erb
<p id="notice"><%= notice %></p>
<% @my_update.each do |updates| %>
<p>
  <strong>Title:</strong>
  <%= updates.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= updates.content %>
</p>

<%= link_to 'Edit', edit_my_update_path(@my_update) %> |
<%= link_to 'Back', my_updates_path %>
<% end %>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
 <% unless current_user.nil? %>
 <% if current_user.has_role? :admin %>
 <h1>Welcome to the admin App</h1>
<%else%>
 <body style= background-color: transparent">
<h1> Welcome all of you</h1><br><br><br>
<p>Click on User to see the users work under you </p><br>
<p>Click on Updates to see all kind of updates </p><br>

</body>
<%end%> 
<%else%>
 <h1>Welcome to the our App</h1>
 <%end%>                
</div>	
 

app/views/users/index.html.erb
<form action="/action_page.php" method="get" id="employee_manager">
  <th><b>Manager: <b></th><th></th>
  <select id="manager">
  <% @managers.select("DISTINCT(manager_user_id)").each do |t| %>

    <option value="<%= t.manager_user_id %>"><%= mangers_email(t.manager_user_id)%></option>
   <% end %>
  </select><td></td><td></td>

  <th><b>Employee:   <b></th><th></th>
  <select id="employee">
    <% @users.each do |user| %>
    <option value="<%= user.id %>"><%= user.email %></option>
    <% end %>
 </select> <br><br>

    

     <button id="save" type="button">Save</button> 

     <input type="hidden" name="employee" value="" id="employee_field">
     <input type="hidden" name="manager" value="" id="manager_field">
</form> 

 <script type="text/javascript">
   $('#save').on('click', function(){
      var employee = $('#employee').val();
      var manager = $('#manager').val();
      $('#employee_field').val(employee);
      $('#manager_field').val(manager);
      $('#employee_manager').submit();
   })
 </script>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>